### ISSUE TITLE
Does Not Work With PHP-FPM

### ISSUE THREAD

**Issue by ghost** [CleanTalk/magento-antispam#5]
app/code/community/Cleantalk/Antispam/Model/lib/cleantalk.class.php

Line 673

$msg->all_headers=json_encode(apache_request_headers());

Won't work on sites with php-fpm

Need added logic to deal with the site not being on straight apache / php 

if ( !function_exists( 'apache_request_headers' ) ) {
		    $msg->all_headers = Zend_Json::encode( $_SERVER );
	    } else {
		    $msg->all_headers = Zend_Json::encode( apache_request_headers() );
	    } 

or change the line to:

$msg->all_headers = Zend_Json::encode( $_SERVER );

**Comment by seansan** [comment]
is this still an issue?

**Comment by ardavydov** [comment]
Hello,

It was fixed here:
https://github.com/CleanTalk/magento-antispam/blob/84de8b4186982df80e9df065198184a243e51e8b/app/code/community/Cleantalk/Antispam/Model/lib/cleantalk.class.php#L989
