### ISSUE TITLE
Add short readme?

### ISSUE THREAD

**Issue by seansan** [CleanTalk/magento-antispam#7]
Would it be possible to add a litttttle more info to the readme?

how to configure?
where does it hook in?
how does it work?
used on what version?

thansk!

**Comment by ardavydov** [comment]
Hello,

We've instruction here:
https://cleantalk.org/help/install-magento

You can download the latest version from releases here and use Magento Connect Manager to upload an archive.

**Comment by Glomberg** [comment]
Megento1 is not supported more. New features not will be implemented.
Jus use this instruction https://cleantalk.org/help/install-magento
